version: '3.3'

services:
  db:
    container_name: devbook_database
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/home/adrielle/Documents/go/dev-book/
volumes:
  my-db:
 
